services:
  webapp.server:
    image: ${DOCKER_REGISTRY-}webappserver
    build:
      context: .
      dockerfile: WebApp/WebApp.Server/Dockerfile

  consumer.pedido:
    image: ${DOCKER_REGISTRY-}consumer-pedido
    build:
      context: .
      dockerfile: Consumer.Pedido/Dockerfile
