services:
  webapp.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__USERNAME=logUser
      - RABBITMQ__PASSWORD=logPwd
      - RABBITMQ__VIRTUALHOST=main
      - RABBITMQ__ConsumerDispatchConcurrency=12
      - RABBITMQ__ClientProvidedName=WebApp
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - consumer
    depends_on:
      - consumer.pedido
      - postgres

  consumer.pedido:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ__PREFETCHCOUNT=10
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__USERNAME=logUser
      - RABBITMQ__PASSWORD=logPwd
      - RABBITMQ__VIRTUALHOST=main
      - RABBITMQ__ClientProvidedName=Consumer.Pedido
      - DB__CONNECTION_STRING=Server=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres;Include Error Detail=true
    networks:
      - consumer

  postgres:
    image: postgres:17.2-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/create-database.sql:/docker-entrypoint-initdb.d/01-create-database.sql
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/01-populate-database.sql
    networks:
      - consumer

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com.br
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_LISTEN_PORT: 7000
    ports:
      - "7000:7000"
    volumes:
      - pgAdmin:/var/lib/pgadmin
    networks:
      - consumer

  rabbitmq:
    hostname: rabbitmq1
    build: ./rabbitmq
    ports:
      - "15672:15672" #Management
      - "5672:5672" #AMQP
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    networks:
      - consumer

volumes:
  pgAdmin:    
  postgres:
  mq_data:
  
networks:
  consumer: